MODEL_STOP=6
GRID_CONST_DIR=$CONST_DIR/icon-leps-7km
IN_GRID_ROOT=$GRID_CONST_DIR/topo_IFS
MODEL_GRID=$GRID_CONST_DIR/ileps_7km_DOM01.nc
MODEL_NCSTORE_ROOT=$GRID_CONST_DIR/ncstorage.ileps_7km
MODEL_GRID_PARENT=$GRID_CONST_DIR/ileps_7km_DOM01.parent.nc
MODEL_GRID_EXTERNAL=$GRID_CONST_DIR/external_parameter_icon_ileps_7km_DOM01_tiles.nc
MODEL_FCAST_GP=125
TIME_STEP=60
if [ "$ECF_TRYNO" -gt 1 ]; then
  TIME_STEP=$(($TIME_STEP/2))
fi

