[ecfvars]

SCHOST = "hpc"
WSHOST = "hpc"
STHOST = "ws1"
STHOST_BKUP = "ws2"
ECF_FILES = "$ECTC_BASE/jobs"
ECF_INCLUDE = "$ECTC_BASE/include"
ECF_HOME = "$ECTC_BASE/ecflow"
ECF_STATUS_CMD = "STHOST=%STHOST% troika monitor %SCHOST% %ECF_JOB%"
ECF_KILL_CMD = "STHOST=%STHOST% troika kill %SCHOST% %ECF_JOB%"
ECF_JOB_CMD = "STHOST=%STHOST% troika submit -o %ECF_JOBOUT% %SCHOST% %ECF_JOB%"
ECF_TRIES = "2"
ECTC_ENS_MEMB = "0"
ECTC_CONF = "$ECTC_BASE/conf" # shell conf files to be sourced
ECTC_WORK = "$TCWORK/work/%SUITE%" # "/ec/%STHOST%/tc/$USER/tcwork/%SUITE%" ?
EC_DISS = "/ec/%STHOST%/tc/zcl/tcwork/lb/ecdiss" # $USER - zcl?

[suiteconf]

deltaday = 30
hours = "0-12:12" # "0" to run only at 00
forecastrange = 132
subsuites = ["ana", "eps", "det"]
pretypes = ["mars", "diss"]
predefault = "mars"
splitretrieve = "Y"
membrange = "0-4"
