# Import ecflow variables in every task

SUITE=%SUITE%
FAMILY=%FAMILY%
TASK=%TASK%
YEAR=%YYYY%
MONTH=%MM%
DAY=%DD%
YMD=%YMD%

GRID=%GRID%
BASEDIR=%BASEDIR%

SCHOST=%SCHOST%
WSHOST=%WSHOST%
MAINDIR=%MAINDIR%
RUNDIR=%RUNDIR%
PERM=%PERM%
DOPOCORSA=%DOPOCORSA%
MYMARSDIR=%MYMARSDIR%
EXECDIR=%EXECDIR%
SORGENTE=%SORGENTE%
FORTRAN=%FORTRAN%
NMEMBER=%NMEMBER%
FCLENGTH=%FCLENGTH%
VERSION=%VERSION%
starthour=%starthour%
TCHOME=%TCHOME%
RESCUE=%RESCUE%
EXEC=%EXEC%
USOHOME=%USOHOME%
WSCRATCH=%WSCRATCH%
