GRID_CONST_DIR=$CONST_DIR/icon-leps-2.5km
IN_GRID_ROOT=$GRID_CONST_DIR/topo_IFS
MODEL_GRID=$GRID_CONST_DIR/ileps_2.5km_DOM01.nc
MODEL_NCSTORE_ROOT=$GRID_CONST_DIR/ncstorage.ileps_2.5km
MODEL_GRID_PARENT=$GRID_CONST_DIR/ileps_2.5km_DOM01.parent.nc
MODEL_GRID_EXTERNAL=$GRID_CONST_DIR/external_parameter_icon_ileps_2.5km_DOM01_tiles.nc
MODEL_FCAST_GP=126
TIME_STEP=24
# if [ "$ECF_TRYNO" -gt 1 ]; then
#   TIME_STEP=$(($TIME_STEP/2))
# fi

