[ecfvars]

SCHOST = "hpc"
WSHOST = "hpc"
STHOST = "$STHOST"
# the following 3 directories must reside in /home/$USER because they
# are needed by the vm which does not see TC filesystems
ECF_FILES = "$ECTC_BASE/jobs"
ECF_INCLUDE = "$ECTC_BASE/include"
ECF_HOME = "$ECTC_BASE/ecflow"
ECF_STATUS_CMD = "STHOST=%STHOST% troika monitor %SCHOST% %ECF_JOB%"
ECF_KILL_CMD = "STHOST=%STHOST% troika kill %SCHOST% %ECF_JOB%"
ECF_JOB_CMD = "STHOST=%STHOST% troika submit -o %ECF_JOBOUT% %SCHOST% %ECF_JOB%"
ECF_TRIES = "2"
ECTC_ENS_MEMB = "0"
ECTC_BIN = "$ECTC_BASE/bin" # suite management executables (not model executables)
ECTC_CONF = "$ECTC_BASE/conf" # shell conf files to be sourced
ECTC_WORKBASE = "%STHOST%/tc/$USER/tcwork"
ECTC_WORK = "%STHOST%/tc/$USER/tcwork/work/%SUITE%"
EC_DISS = "%STHOST%/tc/zcl/tcwork/lb/ecdiss" # $USER - zcl?

[suiteconf]

suitestart = 2023-01-01 00:00:00Z
# suiteback = 15
# suitestop = 2024-01-01 00:00:00Z
suiteduration = 365
hours = "0" # "0" to run only at 00
forecastrange = 120
subsuites = ["det"]
pretypes = ["mars"]
predefault = "mars"
splitretrieve = true
membrange = "0"
timecrit = false
